### ISSUE TITLE
Library Failed to resolve

### ISSUE THREAD

**Issue by rasik1010** [florent37/FiftyShadesOf#1]
Not able to use the gradle of this project.

**Comment by florent37** [comment]
sorry it's updating to jcenter

**Comment by rasik1010** [comment]
okay. May i know when it will be completed ? I am trying to use this amazing library.

**Comment by rasik1010** [comment]
@florent37  May i know when it will be completed  ???

**Comment by florent37** [comment]
sometimes it's instantly, and sometimes it takes few hours, so to be sure try in 2/3 hours

**Comment by rasik1010** [comment]
@florent37  Thanks :) can you post it here, whenever you see it ?  Thanks again 👍

**Comment by florent37** [comment]
btw if you need it urgently : 

``` java
repositories {
    maven {
        url  "http://dl.bintray.com/florent37/maven" 
    }
}

compile 'com.github.florent37:fiftyshadesof:1.0.0'
```

**Comment by florent37** [comment]
it's added 👍
